const QUIZ_QUESTIONS = {
  math: [
    { q: "What is 15 * 12?", a: "180" },
    { q: "What is the square root of 625?", a: "25" },
    { q: "What is 7 * 8 + 3?", a: "59" },
    { q: "Solve for x: 2x + 5 = 17", a: "6" },
    { q: "What is the value of pi to 2 decimal places?", a: "3.14" },
    { q: "What is 144 / 12?", a: "12" },
    { q: "What is 11 squared?", a: "121" },
    { q: "What is 5! (5 factorial)?", a: "120" },
    { q: "What is 2 to the power of 8?", a: "256" },
    { q: "What is 10% of 250?", a: "25" },
    { q: "Solve for y: 3y - 9 = 12", a: "7" },
    { q: "What is 15% of 200?", a: "30" },
    { q: "What is 3 cubed?", a: "27" },
    { q: "What is 9 squared minus 4 squared?", a: "65" },
    { q: "What is 45 + 55?", a: "100" },
    { q: "What is 72 / 8?", a: "9" },
    { q: "What is the LCM of 4 and 6?", a: "12" },
    { q: "What is the GCD of 12 and 18?", a: "6" },
    { q: "What is 1000 - 345?", a: "655" },
    { q: "What is 13 * 13?", a: "169" },
    { q: "What is the sine of 90 degrees?", a: "1" },
    { q: "What is the cosine of 0 degrees?", a: "1" },
    { q: "What is 2/5 as a decimal?", a: "0.4" },
    { q: "What is 3/4 as a percentage? (%)", a: "75" },
    { q: "What is the sum of angles in a triangle?", a: "180" },
    { q: "How many sides does a hexagon have?", a: "6" },
    { q: "What is 8 * 9?", a: "72" },
    { q: "Solve for x: 5x = 45", a: "9" },
    { q: "What is 18 + 14 + 12?", a: "44" },
    { q: "What is 20 * 20?", a: "400" },
    { q: "What is 50 * 5?", a: "250" },
    { q: "What is 1/2 of 1/4?", a: "1/8" },
    { q: "What is 0.5 * 0.5?", a: "0.25" },
    { q: "What is 100 / 4?", a: "25" },
    { q: "What is 12 * 5?", a: "60" },
    { q: "What is the square of 15?", a: "225" },
    { q: "What is 16 * 4?", a: "64" },
    { q: "What is 33 * 3?", a: "99" },
    { q: "What is 10 * 10 * 10?", a: "1000" },
    { q: "What is the cube root of 27?", a: "3" },
    { q: "What is 50 + 75?", a: "125" },
    { q: "What is 9 * 6?", a: "54" },
    { q: "What is 4 * 12?", a: "48" },
    { q: "Solve for a: a/2 = 8", a: "16" },
    { q: "What is 100 - 23?", a: "77" },
    { q: "What is 21 * 2?", a: "42" },
    { q: "What is 11 * 12?", a: "132" },
    { q: "What is the square root of 81?", a: "9" },
    { q: "What is 7 * 7?", a: "49" },
    { q: "What is 120 / 10?", a: "12" },
  ],
  coding: [
    { q: "What data structure uses LIFO? (stack/queue)", a: "stack" },
    { q: "What data structure uses FIFO? (stack/queue)", a: "queue" },
    {
      q: "Which algorithm finds shortest paths in a weighted graph? (e.g. Dijkstra)",
      a: "dijkstra",
    },
    {
      q: "What sorting algorithm has an average O(N log N) time and uses a pivot?",
      a: "quicksort",
    },
    {
      q: "Which traversal visits left, root, then right in a binary tree?",
      a: "inorder",
    },
    { q: "Which graph traversal uses a queue? (bfs/dfs)", a: "bfs" },
    { q: "What term refers to a function calling itself?", a: "recursion" },
    {
      q: "What JS keyword pauses execution of an async function until a Promise resolves?",
      a: "await",
    },
    {
      q: "In OOP, what principle restricts direct access to some of an objects components?",
      a: "encapsulation",
    },
    { q: 'What principle means "many forms" in OOP?', a: "polymorphism" },
    {
      q: "What is the time complexity of searching in a balanced BST? (e.g. O(log N))",
      a: "o(log n)",
    },
    {
      q: "What is the time complexity of accessing an element in an array by index?",
      a: "o(1)",
    },
    {
      q: "What is the time complexity of inserting into a hash table (average)?",
      a: "o(1)",
    },
    { q: "What keyword defines a constant in JavaScript?", a: "const" },
    { q: "What HTML tag is used for the largest heading?", a: "h1" },
    { q: "What CSS property changes text color?", a: "color" },
    { q: "What does CSS stand for? (first word only)", a: "cascading" },
    { q: "What does HTML stand for? (first word only)", a: "hypertext" },
    { q: "What does API stand for? (first word only)", a: "application" },
    { q: "What does SQL stand for? (first word only)", a: "structured" },
    {
      q: "What type of database uses tables and rows? (relational/nosql)",
      a: "relational",
    },
    {
      q: "What keyword adds a new element to the end of a JS array?",
      a: "push",
    },
    { q: "What keyword removes the last element of a JS array?", a: "pop" },
    {
      q: "What keyword adds a new element to the beginning of a JS array?",
      a: "unshift",
    },
    { q: "What keyword removes the first element of a JS array?", a: "shift" },
    { q: "What is the logical AND operator in JavaScript?", a: "&&" },
    { q: "What is the logical OR operator in JavaScript?", a: "||" },
    { q: "What is the strict equality operator in JavaScript?", a: "===" },
    {
      q: "What method converts a JS object to a JSON string?",
      a: "json.stringify",
    },
    {
      q: "What method parses a JSON string into a JS object?",
      a: "json.parse",
    },
    { q: "What does DOM stand for? (first word only)", a: "document" },
    {
      q: "What method selects an element by its ID in JS? (document.?)",
      a: "getelementbyid",
    },
    {
      q: "What method attaches an event handler in JS?",
      a: "addeventlistener",
    },
    { q: "What keyword is used to declare a class in JS?", a: "class" },
    { q: "What JS keyword refers to the current object?", a: "this" },
    {
      q: "What functional method transforms all elements in an array?",
      a: "map",
    },
    {
      q: "What functional method keeps only matching elements in an array?",
      a: "filter",
    },
    {
      q: "What functional method accumulates array values into a single result?",
      a: "reduce",
    },
    {
      q: "What OOP concept allows a class to inherit from another class?",
      a: "inheritance",
    },
    {
      q: "What is a piece of code that runs after an asynchronous operation completes called?",
      a: "callback",
    },
    { q: "What does HTTP stand for? (first word only)", a: "hypertext" },
    { q: "What HTTP method is typically used to retrieve data?", a: "get" },
    { q: "What HTTP method is typically used to create new data?", a: "post" },
    { q: "What protocol secures HTTP traffic?", a: "https" },
    { q: "What command initializes a new git repository?", a: "git init" },
    { q: "What command saves staged changes in git?", a: "git commit" },
    {
      q: "What command downloads code from a remote git repository?",
      a: "git pull",
    },
    {
      q: "What command uploads local commits to a remote git repository?",
      a: "git push",
    },
    { q: "What symbol signifies a single-line comment in JS?", a: "//" },
    { q: "What data type represents true or false?", a: "boolean" },
  ],
  aptitude: [
    {
      q: "If a train 120m long passes a telegraph pole in 6 seconds, what is its speed in m/s?",
      a: "20",
    },
    {
      q: "If 5 machines make 5 widgets in 5 minutes, how many minutes does it take 100 machines to make 100 widgets?",
      a: "5",
    },
    {
      q: "A bat and a ball cost $1.10. The bat costs $1.00 more than the ball. How much does the ball cost in cents?",
      a: "5",
    },
    { q: "What is the next number: 2, 6, 12, 20, 30, ... ?", a: "42" },
    {
      q: "If some Smurfs are Snorks and all Snorks are Borgs, are some Smurfs Borgs? (yes/no)",
      a: "yes",
    },
    {
      q: "If 8 men take 10 hours to build a wall, how many hours for 4 men?",
      a: "20",
    },
    { q: "Divide 30 by half and add 10. What do you get?", a: "70" },
    {
      q: "What is the angle in degrees between the hour and minute hand at 3:15?",
      a: "7.5",
    },
    {
      q: "How many times do the hands of a clock overlap in 24 hours?",
      a: "22",
    },
    {
      q: "If 1=3, 2=3, 3=5, 4=4, 5=4, what is 6=? (Hint: word length)",
      a: "3",
    },
    {
      q: "A man buys a horse for $60, sells for $70, buys back for $80, sells for $90. How much profit in $?",
      a: "20",
    },
    {
      q: "If a triangle has a base of 10 and height of 5, what is its area?",
      a: "25",
    },
    { q: "What is 20% of 30% of 1000?", a: "60" },
    {
      q: "The day before yesterday was two days after Monday. What day is it today?",
      a: "friday",
    },
    { q: 'If A=1, B=2... what is the sum of letters in "CAT"?', a: "24" },
    {
      q: "If 3 cats kill 3 rats in 3 minutes, how many cats kill 100 rats in 100 minutes?",
      a: "3",
    },
    { q: "How many months have 28 days?", a: "12" },
    { q: "What goes up but never comes down?", a: "age" },
    {
      q: "I am an odd number. Take away a letter and I become even. What number am I? (word)",
      a: "seven",
    },
    {
      q: "If you have 3 apples and you take away 2, how many do you have?",
      a: "2",
    },
    { q: "What begins with T, ends with T, and has T in it?", a: "teapot" },
    {
      q: "A farmer has 17 sheep and all but 9 die. How many are left?",
      a: "9",
    },
    {
      q: "If a plane crashes on the border of US and Canada, where do they bury the survivors? (nowhere/us/canada)",
      a: "nowhere",
    },
    { q: "What has a head, a tail, is brown, and has no legs?", a: "penny" },
    {
      q: "What has towns without people, forests without trees, and rivers without water?",
      a: "map",
    },
    {
      q: "I have branches, but no fruit, trunk or leaves. What am I?",
      a: "bank",
    },
    { q: "What has many keys but can not open a single lock?", a: "piano" },
    {
      q: "The more of this there is, the less you see. What is it?",
      a: "darkness",
    },
    {
      q: "What belongs to you, but other people use it more than you?",
      a: "name",
    },
    {
      q: "David’s parents have three sons: Snap, Crackle, and what is the name of the third son?",
      a: "david",
    },
    {
      q: "If you are running in a race and pass the person in second place, what place are you in?",
      a: "second",
    },
    {
      q: "What comes once in a minute, twice in a moment, but never in a thousand years? (letter)",
      a: "m",
    },
    {
      q: "Which is heavier: a ton of bricks or a ton of feathers? (neither/bricks/feathers)",
      a: "neither",
    },
    {
      q: "Before Mt. Everest was discovered, what was the highest mountain in the world?",
      a: "mt. everest",
    },
    {
      q: "If you drop a yellow hat in the Red Sea, what does it become?",
      a: "wet",
    },
    { q: "What has hands but can not clap?", a: "clock" },
    { q: "What has an eye but can not see?", a: "needle" },
    {
      q: "What breaks yet never falls, and what falls yet never breaks? (day and ...)",
      a: "night",
    },
    { q: "What gets wetter as it dries?", a: "towel" },
    { q: "What can you catch but not throw?", a: "cold" },
    { q: "What is always in front of you but can not be seen?", a: "future" },
    {
      q: "What is black when it is clean and white when it is dirty?",
      a: "chalkboard",
    },
    { q: "What has words, but never speaks?", a: "book" },
    { q: "What travels around the world but stays in one spot?", a: "stamp" },
    { q: "What has a bottom at the top?", a: "legs" },
    { q: "What is lighter than what it is made of? (ice/water)", a: "ice" },
    {
      q: "What starts with an e, ends with an e, but only contains one letter?",
      a: "envelope",
    },
    { q: "What gets bigger the more you take away?", a: "hole" },
    { q: "What building has the most stories?", a: "library" },
    { q: "I am full of holes but still hold water. What am I?", a: "sponge" },
  ],
};
